src/backend/verifier/requestCredential.ts, src/frontend/verifier.html
=> SK-759: Update verifier for Discord

src/frontend/verifier.html, src/frontend/verifier.ts, src/frontend/views/Attester/renderAttester.tsx
=> SK-769: update verifier

src/backend/utilities/batchSignAndSubmitAttestation.ts
=> SK-775: timeout for attestations

src/backend/verifier/requestCredential.ts, src/frontend/verifier.html, src/frontend/verifier.ts, yarn.lock
=> SK-689: github in verifier

src/frontend/css/email.css
=> SK-684: another fix for gmail

src/frontend/verifier.ts
=> SK-779: verifier trusts spiritnet DID

src/backend/utilities/fullDid.ts, src/backend/utilities/keypairs.ts
=> SK-726: do key upgrade

src/backend/utilities/fullDid.ts, src/backend/utilities/keypairs.ts
=> SK-726: clean up key update code

src/backend/email/sendEmail.ts, src/backend/endpoints/confirmationHtml.ts, src/backend/twitter/tweets.ts, src/backend/utilities/logger.ts
=> SK-774: more detailed logs

src/backend/server.ts, src/backend/utilities/configuration.ts, src/backend/utilities/keypairs.ts, src/backend/utilities/reportBalance.ts
=> SK-625: Low balance alert

src/backend/server.ts, src/backend/utilities/noAwaitReportBalance.ts
=> noAwaitReportBalance

src/frontend/components/Disconnect/Disconnect.module.css, src/frontend/components/Disconnect/Disconnect.module.css.d.ts, src/frontend/components/Disconnect/Disconnect.tsx, src/frontend/css/styles.css, src/frontend/utilities/broadcastChannels.ts, src/frontend/utilities/session.ts, src/frontend/verifier.ts, src/frontend/views/Attester/Attester.module.css, src/frontend/views/Attester/Attester.module.css.d.ts, src/frontend/views/Attester/Attester.tsx, src/frontend/views/Discord/Discord.test.tsx, src/frontend/views/Email/Email.test.tsx, src/frontend/views/Github/Github.test.tsx, src/frontend/views/Twitter/Twitter.test.tsx
=> SK-750: Other wallets

src/frontend/terms.html
=> SK-811: Terms update for GitHub

src/frontend/views/Attester/Attester.tsx
=> SK-815: make other wallets selectable

src/frontend/views/Twitch/Twitch.module.css
=> SK-722: fix twitch icon

src/frontend/about.html
This changes a sentence in the about.html page.
=> feat: change sentence in about page

src/backend/server.ts
=> SK-808: do not log IPs

src/backend/utilities/batchSignAndSubmitAttestation.ts
=> SK-703: resсue batch attestations again

src/frontend/css/styles.css, src/frontend/index.html
=> SK-781: GitHub Link

src/frontend/privacy.html
SK-899: added Telegram in Part II
=> SK-899: Legal texts update for Telegram credential - privacy

src/backend/utilities/configuration.ts
=> SK-568: Telegram token check

src/frontend/404.html, src/frontend/about.html, src/frontend/privacy.html, src/frontend/terms.html
[SK-781](https://kiltprotocol.atlassian.net/browse/SK-781)
=> SK-781: add GitHub link to all html pages

src/frontend/components/SlowAttestation/SlowAttestation.tsx, src/frontend/paths.ts, src/frontend/views/Attester/Attester.tsx
=> SK-750: default wallet in confirmation

src/frontend/terms.html
=> SK-807: Update terms.html

src/frontend/privacy.html
=> SK-807: Update privacy.html

src/frontend/terms.html
=> SK-807: Update terms.html - part 2

src/frontend/privacy.html, src/frontend/terms.html
=> SK-1096: update privacy

src/frontend/views/Youtube/Youtube.test.tsx, src/frontend/views/Youtube/YoutubeTemplate.tsx, src/frontend/views/Youtube/__snapshots__/YoutubeTemplate.test.tsx.snap
=> SK-1142: YT cred sign in button text change

src/frontend/verifier.html, src/frontend/views/Attester/Attester.tsx
=> SK-1103: add back insta

src/frontend/views/Twitter/TwitterTemplate.tsx, src/frontend/views/Twitter/__snapshots__/TwitterTemplate.test.tsx.snap
=> SK-1157: Open Twitter in new tab

src/frontend/utilities/session.ts
SK-1185
Ensures that messaging still works if Sporran uses a different SDK version.
=> SK-1185: Compatible messages (Hot fix)

src/frontend/views/Telegram/Telegram.module.css
=> SK-1158: Connecting to Telegram button becomes scrollable

src/backend/didConfiguration/didConfigResource.ts, src/backend/utilities/attestClaim.ts, src/backend/utilities/configuration.ts, src/backend/utilities/encryptMessage.ts, src/backend/utilities/fullDid.ts
=> SK-1163: Better handling of undefined own DID

src/backend/utilities/sessionStorage.ts
A new secret for a session invalidates the old ones
=> invalidate old secrets

.github/workflows/dev-ci-cd.yml
This reverts commit 537ed23a6552c78f4760622bf11ba5a4de6024ca.
=> Revert "Update dev-ci-cd.yml"

src/frontend/views/Email/EmailTemplate.test.tsx, src/frontend/views/Email/EmailTemplate.tsx, src/frontend/views/Email/__snapshots__/EmailTemplate.test.tsx.snap
=> SK-1224: Remove LinkBack when email attestation status is 'requested'

.github/workflows/production-restart.yml
This reverts commit 917632103f59558985ae5a2298eb8a8cd874d78d.
=> Revert "Update production-restart.yml"

src/backend/endpoints/metrics.ts
=> SK-1244: init counters

src/backend/email/attestEmail.ts, src/backend/email/attestEmailApi.ts, src/backend/email/authHtmlEmail.ts, src/backend/email/confirmEmail.ts, src/backend/email/quoteEmail.ts, src/backend/email/requestAttestationEmail.ts, src/backend/email/requestAttestationEmailApi.ts, src/backend/email/sendEmail.ts, src/backend/email/sendEmailApi.ts, src/backend/endpoints/paths.ts, src/backend/server.ts, src/frontend/views/Email/Email.module.css, src/frontend/views/Email/Email.module.css.d.ts, src/frontend/views/Email/Email.stories.tsx, src/frontend/views/Email/Email.test.tsx, src/frontend/views/Email/Email.tsx, src/frontend/views/Email/EmailTemplate.test.tsx, src/frontend/views/Email/EmailTemplate.tsx, src/frontend/views/Email/__snapshots__/EmailTemplate.test.tsx.snap, src/frontend/views/Email/useEmailApi.ts
=> SK-1359: Change email flow

src/backend/endpoints/paths.ts, src/backend/server.ts, src/backend/twitter/attestTwitter.ts, src/backend/twitter/attestTwitterApi.ts, src/backend/twitter/claimTwitter.ts, src/backend/twitter/claimTwitterApi.ts, src/backend/twitter/confirmTwitter.ts, src/backend/twitter/quoteTwitter.ts, src/backend/twitter/requestAttestationTwitter.ts, src/backend/twitter/requestAttestationTwitterApi.ts, src/frontend/views/Email/Email.stories.tsx, src/frontend/views/Email/Email.test.tsx, src/frontend/views/Email/Email.tsx, src/frontend/views/Email/EmailTemplate.test.tsx, src/frontend/views/Email/EmailTemplate.tsx, src/frontend/views/Email/__snapshots__/EmailTemplate.test.tsx.snap, src/frontend/views/Twitter/Twitter.module.css, src/frontend/views/Twitter/Twitter.module.css.d.ts, src/frontend/views/Twitter/Twitter.stories.tsx, src/frontend/views/Twitter/Twitter.test.tsx, src/frontend/views/Twitter/Twitter.tsx, src/frontend/views/Twitter/TwitterTemplate.test.tsx, src/frontend/views/Twitter/TwitterTemplate.tsx, src/frontend/views/Twitter/__snapshots__/TwitterTemplate.test.tsx.snap, src/frontend/views/Twitter/useTwitterApi.tsx
=> SK-1360: Change Twitter flow

src/frontend/views/Discord/DiscordTemplate.tsx, src/frontend/views/Discord/__snapshots__/DiscordTemplate.test.tsx.snap, src/frontend/views/Email/EmailTemplate.tsx, src/frontend/views/Email/__snapshots__/EmailTemplate.test.tsx.snap, src/frontend/views/Github/GithubTemplate.tsx, src/frontend/views/Github/__snapshots__/GithubTemplate.test.tsx.snap, src/frontend/views/Telegram/TelegramTemplate.tsx, src/frontend/views/Telegram/__snapshots__/TelegramTemplate.test.tsx.snap, src/frontend/views/Twitch/TwitchTemplate.tsx, src/frontend/views/Twitch/__snapshots__/TwitchTemplate.test.tsx.snap, src/frontend/views/Twitter/TwitterTemplate.tsx, src/frontend/views/Twitter/__snapshots__/TwitterTemplate.test.tsx.snap, src/frontend/views/Youtube/YoutubeTemplate.tsx, src/frontend/views/Youtube/__snapshots__/YoutubeTemplate.test.tsx.snap
=> SK-1225: Don't show back button when preventing navigation

src/frontend/about.html, src/frontend/privacy.html
=> SK-1396: legal text

Dockerfile, scripts/patchVCExport.js
=> SK-1426: fix deployment

src/frontend/css/styles.css
=> SK-1607: fix footer overlap

LICENSE, src/frontend/about.html, src/frontend/privacy.html, src/frontend/terms.html
[SK-1664](https://kiltprotocol.atlassian.net/browse/SK-1664)
[SK-1664]: https://kiltprotocol.atlassian.net/browse/SK-1664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SK-1664: more copyrights

src/backend/utilities/reportBalance.ts
=> SK-1680: Better low balance alerts

package.json, src/backend/email/sendEmail.ts, yarn.lock
=> SK-1007: fix Punycode

src/backend/endpoints/liveness.ts, src/backend/utilities/cryptoCallbacks.ts, src/backend/utilities/fullDid.ts, src/backend/utilities/reportBalance.ts
SK-1698
fixes KILTprotocol/ticket#2439
=> SK-1698: future-proof

scripts/loadTest/encryptedMessage.ts, scripts/loadTest/loadTest.ts, src/backend/discord/confirmDiscord.ts, src/backend/email/sendEmail.ts, src/backend/endpoints/confirm.ts, src/backend/endpoints/requestAttestation.ts, src/backend/github/confirmGithub.ts, src/backend/telegram/confirmTelegram.ts, src/backend/twitch/confirmTwitch.ts, src/backend/twitter/claimTwitter.ts, src/backend/utilities/sessionStorage.ts, src/backend/youtube/confirmYoutube.ts
https://github.com/KILTprotocol/ticket/issues/2628
=> don’t set claim owner

.env.example, src/backend/utilities/configuration.ts, src/backend/utilities/htmlVariants.ts, src/frontend/index.html, src/frontend/utilities/checkTestEnvironment.ts, src/frontend/views/Attester/renderAttester.tsx
https://github.com/KILTprotocol/ticket/issues/2755
=> test environment

src/backend/revoker/scanAttestations.test.ts, src/backend/revoker/scanAttestations.ts, src/backend/revoker/subScan.test.ts, src/backend/revoker/subScan.ts
The Subscan responses where delivering the Attester DID as a HexString of the account, but we need the DID-URI.
=> fix: attestations owner bug

src/backend/revoker/expiredInventory.ts, src/backend/revoker/subScan.test.ts, src/backend/revoker/subScan.ts
In addition to the already merged commits, this branch makes the tests depend on `BLOCK_RANGE_SIZE`, so that potential changes of this value do not require manual test's updates.
=> feat: simpler page reduction
